### ISSUE TITLE
Chrome browser on Android phone

### ISSUE THREAD

**Issue by GabbyCinco** [Jowens96/ecommerce-pattern-library#16]
Very cool website! The visuals look great and everything is linked properly. The only design issue that could be fixed is the header on mobile size. The logo is just a little bit off to the side. Otherwise, the website looks amazing.

<img width="484" alt="Screen Shot 2019-04-15 at 10 11 18 AM" src="https://user-images.githubusercontent.com/31907109/56139454-eaacb200-5f66-11e9-9d01-4a9347c69eb5.png">

**Comment by Jowens96** [comment]
Centered the logo with margin auto. Thank you.
