### ISSUE TITLE
Error:  undefined method `[]' for nil:NilClass & syntax errors

### ISSUE THREAD

**Issue by Jowens96** [Jowens96/ecommerce-pattern-library#5]
@thomasjbradley

Hi Thomas, 

I have encountered a variety of errors with my pattern library recently. Here is what my terminal currently looks like.

<img width="1004" alt="Screen Shot 2019-03-16 at 3 51 47 PM" src="https://user-images.githubusercontent.com/31851871/54480802-6bab4900-4803-11e9-962c-1333f9b70415.png">

Any guidance would be appreciated, either online, in class, or in a meeting.

Thanks,
Jenny

**Comment by thomasjbradley** [comment]
Please commit & push so I can look at the most up-to-date code.

**Comment by Jowens96** [comment]
Apologies, just committed the files.

**Comment by thomasjbradley** [comment]
There are two things that I think are causing it:

1. There isn’t a `name` for this field. Or rather, the `name` is empty:
https://github.com/Jowens96/ecommerce-pattern-library/blob/master/_patterns/cards/config.yml#L11

2. These two lines need to be indented one more level:
https://github.com/Jowens96/ecommerce-pattern-library/blob/master/_patterns/cards/config.yml#L14-L15

**Comment by Jowens96** [comment]
Hi, thank you so much for your help. With your advice and some trouble shooting the problem was resolved. Have a great night!
