### ISSUE TITLE
Page Speed

### ISSUE THREAD

**Issue by michaelqian1995** [Jowens96/ecommerce-pattern-library#9]
Page Speed Fast
Optimization suggestion
Total time expected to be saved (estimated value)
1
Adjust the image size appropriately
11.1 s
2
Provide images in a new generation format
8.55 s
3
Remove blocked rendering resources
0.78 s

**Comment by Jowens96** [comment]
Reduced size of PNGs with the programs ImageAlpha and ImageOptim. Re-exported JPEGs for web through Photoshop.
